config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations',
                                    sessions: 'users/sessions' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "homes#top"
  get "home/about" => "homes#about"
  resources :users, only: [:index, :show, :edit, :update]
  resources :books, only: [:create,:index, :show, :edit, :update, :destroy]
end

app/models/book.rb
class Book < ApplicationRecord
    validates :title, presence: true
    validates :body, presence: true, length:{ maximum: 199 }
	belongs_to :user
	attachment :profile_image
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
	before_action :authenticate_user!
	before_action :correct_user, only: [:edit]

	def create
		@books = Book.all
		@user = User.find_by(id: current_user.id)

		@book = Book.new(book_params)
		@book.user_id = current_user.id
		if @book.save
		   flash[:success] = "You have creatad book successfully."
		   redirect_to book_path(@book)
		else
		   render 'index'
		end
	end

	def index
		@books = Book.all
		@user = User.find_by(id: current_user.id)
		@book = Book.new
	end

	def show
		@deta = Book.find(params[:id])
		@user = @deta.user
		@book = Book.new
	end

	def edit
		@book = Book.find(params[:id])
	end

	def update
		@book = Book.find(params[:id])
		if @book.update(book_params)
			flash[:success] = "You have updated book successfully."
			redirect_to book_path(@book)
	    else
	    	render 'edit'
	    end
	end

	def destroy
		@book = Book.find(params[:id])
		@book.delete
		redirect_to books_path
	end

	private
	def book_params
		params.require(:book).permit(:title, :body)
	end

	def correct_user
		book = Book.find(params[:id])
		user = book.user
		if current_user != user
			redirect_to books_path
		end
	end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_left_content.html.erb
<div class="col-xs-3">
    <h2>User info</h2>

    <%= attachment_image_tag user, :profile_image, format: 'jpeg', fallback:"no_image.jpg",  size: "100x100"  %>
    <table class="table">
	    <tbody>
		    <tr>
			    <th>name</th>
			    <th><%= user.name %></th>
		    </tr>
		    <tr>
			    <th>introduction</th>
			    <th><%= user.introduction %></th>
		    </tr>
	    </tbody>
    </table>
    <div class="row">
    	<%= link_to '',  edit_user_path(user), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench" %>
    </div>


    <h2>New book</h2>
    <%= form_for(book) do |f| %>
        <div class="field row">
        	<label>Title</label><br>
            <%= f.text_field :title, class: "col-xs-12 book_title" %>
        </div>
        <div class="field row">
        	<label>Option</label><br>
            <%= f.text_area :body, class: "col-xs-12 book_opinion" %>
        </div>
        <div class="field row">
        	<%= f.submit "Create Book", class: "col-xs-12 btn btn-primary" %>
        </div>
    <% end %>
</div>


app/views/books/edit.html.erb
<div class="row">


  <div class="col-md-6 col-md-offset-3">
     <h1>Editing Book</h1>

    <% if @book.errors.any? %>
      <div id="error_explanation">
        <h3><%= @book.errors.count %> errors prohibited this book from being saved:</h3>
        <ul>
          <% @book.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <%= form_for(@book) do | f | %>

      <div class="field row">
        <label>Titile</label><br>
        <%= f.text_field :title, class: "col-xs-12" %>
      </div>
      <div class="field row">
        <label>Opinion</label><br>
        <%= f.text_area :body, class: "col-xs-12" %>
      </div>
      <div class="actions row">
        <%= f.submit "Update Book", class: "col-xs-12 btn btn-primary" %>
      </div>

    <% end %>
    <%= link_to "Show", book_path(@book) %><span> | </span><%= link_to "Back",books_path %>
  </div>
<div>

app/views/books/index.html.erb
<% if @book.errors.any? %>
    <div id="error_explanation">
        <h3><%= @book.errors.count %> errors prohibited this obj from being saved:</h3>
        <ul>
            <% @book.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
        </ul>
    </div>
<% end %>

<div class="row">

	<%= render partial: 'books/left_content', locals: { user: @user, book: @book } %>

	<div class="col-xs-9">

        <h2>Books</h2>
        <table class="table">
	        <thead>
		        <tr>
			        <th></th>
			        <th>title</th>
		            <th>opinion</th>
		            <th colspan ="3"></th>
		        </tr>
	        </thead>
	        <tbody>
		        <% @books.each do |book| %>
		            <tr>
		                <td>
		        	        <%= link_to user_path(book.user_id) do %>
		        	            <%= attachment_image_tag book.user , :profile_image, format: 'jpeg', fallback:"no_image.jpg", size: "40x40" %>
		        	        <% end %>
		                </td>
		                <td><%= link_to book.title , book_path(book) %></td>
		                <td><%= book.body %></td>
		            </tr>
		        <% end %>
	        </tbody>
        </table>
    </div>
</div>

app/views/books/show.html.erb
<div class="row">
	<%= render partial: 'books/left_content', locals: { user: @user, book: @book } %>
	<div class="col-xs-9">
		<h2>Book detail</h2>
        <table class="table">
	        <tbody>
		        <tr>
		            <td>
		            	<%= link_to user_path(@user) do %>
		    	            <%= attachment_image_tag @deta.user , :profile_image, format: 'jpeg', fallback:"no_image.jpg", size: "100x100" %>
		    	            <br>
		    	            <%= @deta.user.name %>
		    	        <% end %>
		    	    </td>
		            <td><%= link_to @deta.title, book_path(@deta) %></td>
		            <td><%= @deta.body %></td>
		            <% if @user.id == current_user.id %>
		                <td><%= link_to 'Edit', edit_book_path(@deta), class: "btn-sm btn-success"  %></td>
		                <td><%= link_to 'Destroy',  book_path(@deta), method: :delete, data: { confirm: '本当に消しますか？'}, class: "btn-sm btn-danger" %></td>
		            <% end %>
		        </tr>
	        </tbody>
        </table>
	</div>
</div>
