config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations',
                                    sessions: 'users/sessions' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "homes#top"
  get "home/about" => "homes#about"
  resources :users, only: [:index, :show, :edit, :update]
  resources :books, only: [:create,:index, :show, :edit, :update, :destroy]
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <nav class="nav navbar-nav navbar-left">
          <span>Bookers</span>
        </nav>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
              <li>
                <%= link_to ' Home', user_path(current_user.id), class: "glyphicon glyphicon-home" %>
              </li>
              <li><%= link_to ' Users', users_path, class: "glyphicon glyphicon-user" %></li>
              <li><%= link_to ' Books', books_path, class: "glyphicon glyphicon-book" %></li>
             <li><%= link_to ' logout', destroy_user_session_path, method: :delete, class: "glyphicon glyphicon-log-out" %></li>
            <% else %>
              <li><%= link_to ' Home', '/', class: "glyphicon glyphicon-home home"%></li>
              <li><%= link_to ' About', home_about_path, class: "glyphicon glyphicon-link about"%></li>
              <li><%= link_to ' sign up', new_user_registration_path,class: "glyphicon glyphicon-edit sign_up" %></li>
              <li><%= link_to ' login', new_user_session_path, class: "glyphicon glyphicon-log-in sign-in" %></li>
            <% end %>
          </ul>
        </nav>
      </div>
    </header>

    <div class="body">
      <div class="container">
        <p id="notice"><%= flash[:notice] %></p>
        <p><%= flash[:success] %></p>
        <%= yield %>
      </div>
    </div>

    <footer>
      <div class="container">
        <div class="row">
          <div class="col-xs-3 col-xs-offset-9">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>

  </body>
</html>